#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/Linka.Api/Linka.Api.csproj", "src/Linka.Api/"]
COPY ["src/Linka.Application/Linka.Application.csproj", "src/Linka.Application/"]
COPY ["src/Linka.Domain/Linka.Domain.csproj", "src/Linka.Domain/"]
COPY ["src/Linka.Infrastructure/Linka.Infrastructure.csproj", "src/Linka.Infrastructure/"]
RUN dotnet restore "./src/Linka.Api/Linka.Api.csproj"
COPY . .
WORKDIR "/src/src/Linka.Api"
RUN dotnet build "./Linka.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Linka.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Linka.Api.dll"]